version: '3'

services:
  mail:
    build: mail
    depends_on:
      - database
    environment: 
      - MAIL_HOSTNAME=s2.ehaupt.de
      - MAIL_DOMAIN=ehaupt.de
      - SQL_USER=mail
      - SQL_PASSWORD=postfix
      - SQL_HOST=database
      - SQL_DB=mail
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "143:143"
      - "993:993"
    volumes:
      - ./fullchain.pem:/cert/fullchain.pem:ro
      - ./privkey.pem:/cert/privkey.pem:ro
      - mailStore:/var/vmail


  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mail
      POSTGRES_USER: mail
      POSTGRES_PASSWORD: postfix
    volumes:
      - dbStore:/var/lib/postgresql/data

  postfixadmin:
    depends_on:
      - database
    image: postfixadmin
    ports:
      - 8001:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_DB_HOST: database
      POSTFIXADMIN_DB_NAME: mail
      POSTFIXADMIN_DB_USER: mail
      POSTFIXADMIN_DB_PASSWORD: postfix
      POSTFIXADMIN_SETUP_PASSWORD: '$$2y$$10$$YTl0yAU7RIajgxzUrs3YTeGWVczAgnch5Uj2.oDcKt2EQi8xVIXdC'

volumes: 
  mailStore: {}
  dbStore: {}