services:
  postfix:
    build: postfix
    depends_on:
      - database
      - opendkim
    restart: always
    env_file: 
      - .env
    environment: 
      - SQL_HOST=database
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - "${CERT_LOCATION_CHAIN}:/cert/fullchain.pem:ro"
      - "${CERT_LOCATION_KEY}:/cert/privkey.pem:ro"
      - mailStore:/var/vmail

  dovecot:
    build: dovecot
    depends_on:
      - database
    restart: always
    env_file: 
      - .env
    environment: 
      - SQL_HOST=database
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - "${CERT_LOCATION_CHAIN}:/cert/fullchain.pem:ro"
      - "${CERT_LOCATION_KEY}:/cert/privkey.pem:ro"
      - mailStore:/var/vmail

  opendkim:
    image: instrumentisto/opendkim:latest
    restart: always
    env_file: 
      - .env
    volumes:
      - ./opendkim/config:/etc/opendkim/conf
      - ./opendkim/keys:/etc/opendkim/keys

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: "${SQL_DB}"
      POSTGRES_USER: "${SQL_USER}"
      POSTGRES_PASSWORD: "${SQL_PASSWORD}"
    volumes:
      - dbStore:/var/lib/postgresql/data

  postfixadmin:
    depends_on:
      - database
    image: postfixadmin
    ports:
      - 8001:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_DB_HOST: database
      POSTFIXADMIN_DB_NAME: "${SQL_DB}"
      POSTFIXADMIN_DB_USER: "${SQL_USER}"
      POSTFIXADMIN_DB_PASSWORD: "${SQL_PASSWORD}"
      POSTFIXADMIN_SETUP_PASSWORD: "${POSTFIXADMIN_SETUP_PASSWORD}"

volumes: 
  mailStore: {}
  dbStore: {}